<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>launcher.ico</ApplicationIcon>

		<!-- Настройки для portable билда -->
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>

		<!-- Указываем, что файлы должны быть рядом с exe -->
		<PublishDir>$(OutputPath)\publish\</PublishDir>
		<SupportedOSPlatformVersion>10.0.26100.0</SupportedOSPlatformVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CmlLib.Core" Version="4.0.6" />
		<PackageReference Include="CmlLib.Core.Installer.Forge" Version="1.1.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="System.Text.Json" Version="9.0.9" />
	</ItemGroup>

	<!-- Включаем иконку в сборку -->
	<ItemGroup>
		<Content Include="launcher.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

</Project>